/*
@title: Unlock the Door
@author: Aditi Ranjan
*/

const player = "p";
const wall = "w";
const key = "k";
const door = "d";
const goal = "g";

setLegend(
  [player, bitmap`
................
................
................
....000000000...
....0.......0...
....0..0.0..0...
....0.......0...
....0..000..0...
....0.......0...
....000000000...
........0.......
.....00.0.00....
......00000.....
........0.......
......00000.....
......00000.....`],
  [wall, bitmap`
2CCCCCCC2CCCCCCC
2CCCCCCC2CCCCCCC
2CCCCCCC2CCCCCCC
2CCCCCCC2CCCCCCC
2222222222222222
CCCC2CCCCCC2CCCC
CCCC2CCCCCC2CCCC
CCCC2CCCCCC2CCCC
CCCC2CCCCCC2CCCC
2222222222222222
CCCCCC2CCCCCCCCC
CCCCCC2CCCCCCCCC
CCCCCC2CCCCCCCCC
CCCCCC2222222222
CCCCCC2CCCCCCCCC
CCCCCC2CCCCCCCCC`],
  [key, bitmap`
................
................
................
................
................
......333.......
......3.3.......
......333.......
.......3........
.......3........
.......3.3......
.......333......
................
................
................
................`],
  [door, bitmap`
................
................
...CCCCCCCCCCC..
...C000000000C..
...C000000000C..
...C000000000C..
...C000000000C..
...C000000660C..
...C000000660C..
...C000000000C..
...C000000000C..
...C000000000C..
...C000000000C..
...CCCCCCCCCCC..
................
................`],
  [goal, bitmap`
................
................
................
................
....CCCCCCCC....
....C......C....
....CC....CC....
.....C....C.....
.....C....C.....
...CCC7777CCC...
...C77777777C...
...C77777777C...
...C77777777C...
...C55555555C...
...C55555555C...
...CCCCCCCCCC...`]
);

setSolids([player, wall, door]);

let hasKey = false;

let level = 0;
const levels = [
  map`
p.w........
..w....k.w.
..w...w.w..
..w...w.w..
..w...w..w.
..w...w..d.
......w....
..w...w....
..w.w.w....
..w.w.g....`,
  map`
pw.........
.w.........
....w...k..
.w..w......
.w..w......
....w..w...
.w..w..w.d.
.w..w..w...
.w..w..w...
.w..g..w...`
];

setMap(levels[level]);

onInput("w", () => {
  getFirst(player).y -= 1;
});

onInput("a", () => {
  getFirst(player).x -= 1;
});

onInput("s", () => {
  getFirst(player).y += 1;
});

onInput("d", () => {
  getFirst(player).x += 1;
});

afterInput(() => {
  const playerPos = getFirst(player);
  const keyPos = getFirst(key);
  const doorPos = getFirst(door);
  const goalPos = getFirst(goal);

  // Check if player picks up the key
  if (playerPos.x === keyPos.x && playerPos.y === keyPos.y) {
    hasKey = true;
    keyPos.remove();
  }

  // Check if player reaches the door
  if (hasKey && playerPos.x === doorPos.x && playerPos.y === doorPos.y) {
    doorPos.remove();
  }

  // Check if player reaches the goal
  if (playerPos.x === goalPos.x && playerPos.y === goalPos.y) {
    level++;
    hasKey = false;

    if (level < levels.length) {
      setMap(levels[level]);
    } else {
      addText("You Win!", { x: 4, y: 4, color: color`3` });
    }
  }
});
